"""
Deposition Summary Report Generator — reads topics CSV, produces formatted Excel.

Usage:
  .venv/bin/python3 python/depo_report.py \
    --input-file /tmp/depo_test/slug_depo_topics.csv \
    --output-file /tmp/depo_test/summary.xlsx \
    [--case-name "Smith v. Jones"]
"""

import argparse
import csv
import os
import re
from datetime import date
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter

GREEN   = PatternFill('solid', fgColor='669966')
BLACK   = PatternFill('solid', fgColor='212121')
DARK    = PatternFill('solid', fgColor='37474F')
LTGRAY  = PatternFill('solid', fgColor='F5F5F5')
FAINT   = PatternFill('solid', fgColor='FAFAFA')

WHITE_BOLD = Font(bold=True, color='FFFFFF', size=11)
WHITE_SM   = Font(color='FFFFFF', size=9)

ACCENT_COLOR = '1565C0'


def thin_side():
    return Side(style='thin', color='DDDDDD')


def thin_border():
    s = thin_side()
    return Border(left=s, right=s, top=s, bottom=s)


def accent_border():
    """Left-side accent border for legally significant rows."""
    thick = Side(style='medium', color=ACCENT_COLOR)
    thin = thin_side()
    return Border(left=thick, right=thin, top=thin, bottom=thin)


def format_page(start, end):
    try:
        s = int(start)
        e = int(end)
    except (ValueError, TypeError):
        return str(start)
    return f"p. {s}–{e}" if e > s else f"p. {s}"


def derive_case_name(input_file: str) -> str:
    stem = os.path.splitext(os.path.basename(input_file))[0]
    # strip trailing _depo_topics
    stem = re.sub(r'_depo_topics$', '', stem, flags=re.IGNORECASE)
    return stem.replace('_', ' ').title()


def load_topics(input_file: str):
    rows = []
    with open(input_file, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            rows.append(row)
    return rows


def write_report(topics, case_name, output_file):
    wb = Workbook()
    ws = wb.active
    ws.title = 'Deposition Summary'

    # Column widths
    ws.column_dimensions['A'].width = 12   # PAGE
    ws.column_dimensions['B'].width = 35   # SUBJECT
    ws.column_dimensions['C'].width = 90   # SUMMARY
    ws.column_dimensions['D'].width = 30   # SIGNIFICANCE

    col_count = 4

    def merge_write(row_num, value, fill, font, alignment='center', italic=False):
        ws.merge_cells(f'A{row_num}:D{row_num}')
        cell = ws[f'A{row_num}']
        cell.value = value
        cell.fill = fill
        f = Font(
            bold=font.bold,
            color=font.color,
            size=font.size,
            italic=italic,
        )
        cell.font = f
        cell.alignment = Alignment(
            horizontal=alignment, vertical='center', wrap_text=True
        )
        ws.row_dimensions[row_num].height = 22

    # --- Header block (rows 1–3) ---
    merge_write(1, case_name.upper(), GREEN, WHITE_BOLD)
    ws.row_dimensions[1].height = 24

    total_topics = len(topics)
    pages = sorted(set(
        int(r['page_start']) for r in topics if r.get('page_start')
    ))
    page_count = (max(pages) - min(pages) + 1) if pages else 0

    merge_write(
        2,
        f"DEPOSITION SUMMARY — {total_topics} topics across {page_count} pages",
        BLACK,
        WHITE_BOLD,
    )

    merge_write(
        3,
        f"Generated by FPAmed Box Index Tool — {date.today().strftime('%B %d, %Y')}",
        DARK,
        WHITE_SM,
    )
    ws.row_dimensions[3].height = 18

    # Row 4: spacer
    ws.row_dimensions[4].height = 6

    # --- Column headers (row 5) ---
    headers = ['PAGE', 'SUBJECT', 'SUMMARY', 'SIGNIFICANCE']
    header_fill = PatternFill('solid', fgColor='455A64')
    header_font = Font(bold=True, color='FFFFFF', size=10)
    for col, h in enumerate(headers, 1):
        c = ws.cell(row=5, column=col, value=h)
        c.fill = header_fill
        c.font = header_font
        c.alignment = Alignment(horizontal='center', vertical='center')
        c.border = thin_border()
    ws.row_dimensions[5].height = 20

    # --- Data rows ---
    for i, row in enumerate(topics):
        r_num = i + 6
        has_sig = bool(row.get('legal_significance', '').strip())
        row_fill = LTGRAY if i % 2 == 0 else PatternFill()

        page_label = format_page(row.get('page_start', ''), row.get('page_end', ''))
        values = [
            page_label,
            row.get('subject', ''),
            row.get('summary', ''),
            row.get('legal_significance', ''),
        ]

        for col, val in enumerate(values, 1):
            c = ws.cell(row=r_num, column=col, value=val)
            c.fill = row_fill
            c.border = accent_border() if has_sig else thin_border()
            c.alignment = Alignment(
                horizontal='center' if col == 1 else 'left',
                vertical='top',
                wrap_text=True,
            )

        # Estimate row height from summary length
        summary_len = len(row.get('summary', ''))
        est_lines = max(1, summary_len // 80)
        ws.row_dimensions[r_num].height = max(30, est_lines * 14)

    # --- Footer (2 rows after last data row) ---
    last_data_row = len(topics) + 5
    footer_row = last_data_row + 2
    ws.merge_cells(f'A{footer_row}:D{footer_row}')
    footer = ws[f'A{footer_row}']
    footer.value = (
        "NOTES ON METHODOLOGY: This summary was generated by processing the transcript page by page "
        "using Box AI. Every page was individually examined. Topic count and page citations reflect "
        "the automated pipeline output and should be verified against the source transcript for any "
        "testimony that will be cited in a filing or expert report."
    )
    footer.fill = LTGRAY
    footer.font = Font(italic=True, size=9, color='666666')
    footer.alignment = Alignment(
        horizontal='left', vertical='center', wrap_text=True, indent=1
    )
    ws.row_dimensions[footer_row].height = 42

    wb.save(output_file)
    print(f'Report saved → {output_file}', flush=True)
    print(f'  Topics:      {total_topics}', flush=True)
    print(f'  Page range:  {min(pages) if pages else "?"} – {max(pages) if pages else "?"}', flush=True)


def main():
    parser = argparse.ArgumentParser(description='Deposition Summary Report Generator')
    parser.add_argument('--input-file', required=True, help='Path to *_depo_topics.csv')
    parser.add_argument('--output-file', required=True, help='Path for output .xlsx')
    parser.add_argument('--case-name', default=None, help='Override case name in header')
    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        print(f'ERROR: Input file not found: {args.input_file}', flush=True)
        raise SystemExit(1)

    topics = load_topics(args.input_file)
    if not topics:
        print('ERROR: No topics found in input file.', flush=True)
        raise SystemExit(1)

    case_name = args.case_name or derive_case_name(args.input_file)
    write_report(topics, case_name, args.output_file)


if __name__ == '__main__':
    main()
